name: Build and deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm install
      run: npm install
      # This triggers `gatsby build` script in "package.json"
    - name: Gatsby build
      run: npm run build
    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.MDD_DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: '-p 2233'
        src: 'public/'
        dest: 'lopoit@s3.supportedns.com:closerinti.me'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"   
